### PR TITLE
multi-arch oci build approach for convenient ghcr package deployment

### PR DESCRIPTION
**Pull request by renlord**
you asked for it, you got it!

### CODE REVIEW

**Comment by renlord** [comment]
closes https://github.com/hugomd/cloudflare-ddns/issues/8

**Comment by renlord** [comment]
you might want to edit the Dockerfile and add the label to pin the packages directly with this repo.

**Comment by hugomd** [comment]
> you might want to edit the Dockerfile and add the label to pin the packages directly with this repo.

What do you mean by label?

**Review by hugomd — APPROVED** [review]
This looks great, thanks @renlord !

**Comment by renlord** [comment]
@hugomd this label -- https://docs.github.com/en/packages/guides/connecting-a-repository-to-a-container-image#connecting-a-repository-to-a-container-image-on-the-command-line

**Pull request merged**
