### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by stek29**

### CODE REVIEW

**Comment by stek29** [comment]
@hugomd do you mind looking into it?

**Comment by hugomd** [comment]
@stek29 absolutely, I'll try to get to it in the next couple of days 👍🏻

**Review by hugomd — APPROVED** [review]
This looks great, thanks for the PR @stek29, and sorry it took me so long to get around to it!

**Comment by hugomd** [comment]
@stek29 this has been deployed, you'll just need to use the latest version: `hugomd/cloudflare-ddns:2.1.0`

@nchlswhttkr @renlord I think you were also both interested in IPv6 support ^

**Comment by nchlswhttkr** [comment]
I’m not running anything on IPv6 at the moment, but this will be great the next time I’m trying something on Vultr’s $2.50 instances. Cheers!

In related good news, `v2.1.0` is working fine for me too. I switched over to downloading the binary from the GitHub release rather than compiling from source, and the only hiccup I’ve found so far was making sure that `musl-libc` was installed. Lovely little piece of software. :heart:

**Pull request merged**
